
MODEL:
  NAME:
  CONV2D:
    IN_CHANNEL:
    STRIDE:
    KERNEL_SIZE:
    PADDING:
    HIDDEN_DIMS:
    DILATION:
  MAX_POOLING:
    STRIDE:
    KERNEL:
  ACTIVATE:
    NAME:
  OPRIMIZER:
    NAME:
  SCHEDULER:
    STEP_SIZE:
    GAMMA:
  LOSS:
    NAME:
  INFERENCE:
    NAME:

TRANSFORMS:
  RESIZE:
    PROBABILITIES:
      ONE_OF_PROBABILITY:
        VERTICALFLIP:
    CROP:
    PIXEL_MEAN:
    PIXEL_STD:

SOLVER:
  DEVICE:
  BATCH_SIZE:
  LOG:
    LEVEL:
    STEPS:
  EVALUATION:
    STEPS:
  EPOCHS:

DATA:
  NAME:
    LOADER:
      NUM_WORKERS:
    DATASET:
      ROOT_DIR:

OUTPUT_DIR: